name: PR Build and Test

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node.JS ${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Test
        run: |
          yarn lint
          yarn test
  preRelease:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Version
        env:
          PRE_ID: pr-${{ github.event.number }}-${{ github.run_id }}
        run: npm version prepatch --git-tag-version=false --preid="${PRE_ID}-$(date '+%s')"
      - name: PrePublish
        env:
          NODE_AUTH_TOKEN: ${{secrets.LIFEOMIC_NPM_TOKEN}}
          PR_TAG: pr-${{ github.event.number }}
        run: |
          yarn build
          npm publish ./dist/ --tag "${PR_TAG}" 
